<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xf="http://www.w3.org/2005/xpath-functions">
  <xsl:output method="text" indent="yes" />

  <xsl:param name="orderSequence"/>
  <xsl:param name="account"/>

  <!-- Step1: Pre-process data mappings to lossless XML -->
  <!--
    This is assuming that the mapping serializer/deserializer is being introduced
    separately for when target document is JSON, where serializer directly produce lossless
    XML in preparation for xml-to-json() transformation. Note that it uses special elements
    for JSON lossless format such as xf:map and xf:array.
  -->
  <xsl:variable name="mappedLosslessXml">
    <xf:map>
      <xf:string key="OrderId"><xsl:value-of select="upper-case(concat('ORD-', $account/Account/@AccountId, '-', $orderSequence))"/></xf:string>
      <xf:string key="OrderPerson"><xsl:value-of select="$account/Account/@AccountId, ':', $account/Account/Name"/></xf:string>
      <xf:map key="ShipTo">
        <xf:string key="Name"><xsl:value-of select="$account/Account/Name"/></xf:string>
        <xf:map key="Address">
          <xf:string key="Street"><xsl:value-of select="$account/Account/Address/Street"/></xf:string>
          <xf:string key="City"><xsl:value-of select="$account/Account/Address/City"/></xf:string>
          <xf:string key="State"><xsl:value-of select="$account/Account/AddressState"/></xf:string>
          <xf:string key="Country"><xsl:value-of select="$account/Account/Address/Country"/></xf:string>
        </xf:map>
      </xf:map>
      <xf:array key="Item">
        <xsl:for-each select="/Cart/Item">
          <xf:map>
            <xf:string key="Title"><xsl:value-of select="Title"/></xf:string>
            <xf:number key="Quantity"><xsl:value-of select="Quantity"/></xf:number>
            <xf:number key="Price"><xsl:value-of select="Price"/></xf:number>
          </xf:map>
        </xsl:for-each>
      </xf:array>
    </xf:map>
  </xsl:variable>

  <!-- Step2: Converts lossless XML to JSON output -->
  <xsl:template
    match="/">
    <xsl:value-of
      select="xml-to-json($mappedLosslessXml)" />
  </xsl:template>

</xsl:stylesheet>
