<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xf="http://www.w3.org/2005/xpath-functions">
  <xsl:output method="text" indent="yes" />

  <xsl:param name="kaotoDataMapperBody" />

  <xsl:variable
          name="body-xml" select="json-to-xml($kaotoDataMapperBody)" />

  <!-- JSON schema
    {
      type: ["string", "number"]
    }
  -->
  <xsl:variable name="mapped-lossless-xml">
    <xsl:if test="$body-xml/xf:string">
      <xf:string><xsl:value-of select="$body-xml/xf:string"/></xf:string>
    </xsl:if>
    <xsl:if test="$body-xml/xf:number">
      <xf:number><xsl:value-of select="$body-xml/xf:number"/></xf:number>
    </xsl:if>
  </xsl:variable>

  <!-- Step4: Converts lossless XML to JSON output -->
  <xsl:template match="/">
    <xsl:value-of select="xml-to-json($mapped-lossless-xml)" />
  </xsl:template>

</xsl:stylesheet>
